---
# tasks file for mysql
- name: Install MySQL
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - mysql-server
    - mysql-client

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Create mysql user
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL
  become: yes
