---
# tasks file for apache
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - php
    - libapache2-mod-php
    - php-mysql
    - php-curl 
    - php-gd
    - php-mbstring
    - php-mcrypt
    - php-xml
    - php-xmlrpc
    - python-mysqldb
